"""Removed hashed_password from User

Revision ID: 0040541cf644
Revises: initial_migration
Create Date: 2025-06-04 16:51:41.685180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0040541cf644'
down_revision: Union[str, None] = 'initial_migration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('login_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_history_id'), 'login_history', ['id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.alter_column('chat_messages', 'order_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chat_messages', 'sender_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chat_messages', 'receiver_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chat_messages', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('chat_messages', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('chat_messages', 'message_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chat_messages', 'is_read',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_foreign_key(None, 'chat_messages', 'orders', ['order_id'], ['order_id'])
    op.alter_column('orders', 'order_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'customer_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'service_provider_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'service_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('orders', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=True)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=False)
    op.alter_column('orders', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('orders', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'service_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'service_provider_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'customer_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'order_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.alter_column('chat_messages', 'is_read',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chat_messages', 'message_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat_messages', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('chat_messages', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('chat_messages', 'receiver_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat_messages', 'sender_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat_messages', 'order_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_login_history_id'), table_name='login_history')
    op.drop_table('login_history')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
