"""Increase all String columns to 255

Revision ID: e2edf212deaf
Revises: 0040541cf644
Create Date: 2025-06-05 16:06:38.690174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e2edf212deaf'
down_revision: Union[str, None] = '0040541cf644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=True)
    # ### end Alembic commands ###
